# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: self

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'az-sp-devops'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 
    

- task: Docker@2
  inputs:
    containerRegistry: 'SCDockerToDevops'
    command: 'login'


- task: Docker@2
  inputs:
    containerRegistry: 'AcrToDevopsConnection'
    repository: 'nginx'
    command: 'push'
    tags: |
         latest